[build]
target = "index.html"

[serve]
address = "0.0.0.0"
port = 8081

[[proxy]]
backend = "http://localhost:3000/assets/apexcharts.min.js"
rewrite = "/assets/apexcharts.min.js"

[[proxy]]
backend = "http://localhost:3000/assets/apexcharts.min.css"
rewrite = "/assets/apexcharts.min.css"

[[proxy]]
backend = "http://localhost:3000/assets/mermaid.min.js"
rewrite = "/assets/mermaid.min.js"

[[proxy]]
backend = "http://localhost:3000/assets/main.css"
rewrite = "/assets/main.css"

[[proxy]]
backend = "http://localhost:3000/assets/custom.css"
rewrite = "/assets/custom.css"
